# Generated by Django 5.2 on 2025-05-08 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Post",
        ),
    ]
